In [1]:
pwd

'C:\\Users\\Vishesh Raina\\Desktop\\Online Courses\\Kaggle'

In [2]:
import pandas as pd
#import quandl, math, datetime
import numpy as np
from sklearn import preprocessing,  svm
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
import os
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from matplotlib import style

In [3]:
data=pd.read_csv("train.csv")

In [4]:
data.head(7)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000

In [5]:
""""for col in data.columns:
    print (col, ':' ,len(data[col].unique()) ,' unique labels exist in this column')"""

'"for col in data.columns:\n    print (col, \':\' ,len(data[col].unique()) ,\' unique labels exist in this column\')'

In [6]:
data['MoSold']

0        2
1        5
2        9
3        2
4       12
        ..
1455     8
1456     2
1457     5
1458     4
1459     6
Name: MoSold, Length: 1460, dtype: int64

In [7]:
data=data.drop(['Id','Street','Alley','Utilities','PoolQC','Fence','MiscFeature','PoolArea','MasVnrType'],axis=1)
data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Reg,Lvl,Inside,Gtl,CollgCr,Norm,...,61,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Reg,Lvl,FR2,Gtl,Veenker,Feedr,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,IR1,Lvl,Inside,Gtl,CollgCr,Norm,...,42,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,IR1,Lvl,Corner,Gtl,Crawfor,Norm,...,35,272,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,IR1,Lvl,FR2,Gtl,NoRidge,Norm,...,84,0,0,0,0,12,2008,WD,Normal,250000

In [8]:
le = preprocessing.LabelEncoder()
encoded_labels=le.fit_transform(data["Neighborhood"])
encoded_labels
data=data.drop(["Neighborhood"],axis=1)
data["Neighborhood"]=encoded_labels
data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LandContour,LotConfig,LandSlope,Condition1,Condition2,...,EnclosedPorch,3SsnPorch,ScreenPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Neighborhood
0,60,RL,65.0,8450,Reg,Lvl,Inside,Gtl,Norm,Norm,...,0,0,0,0,2,2008,WD,Normal,208500,5
1,20,RL,80.0,9600,Reg,Lvl,FR2,Gtl,Feedr,Norm,...,0,0,0,0,5,2007,WD,Normal,181500,24
2,60,RL,68.0,11250,IR1,Lvl,Inside,Gtl,Norm,Norm,...,0,0,0,0,9,2008,WD,Normal,223500,5
3,70,RL,60.0,9550,IR1,Lvl,Corner,Gtl,Norm,Norm,...,272,0,0,0,2,2006,WD,Abnorml,140000,6
4,60,RL,84.0,14260,IR1,Lvl,FR2,Gtl,Norm,Norm,...,0,0,0,0,12,2008,WD,Normal,250000,15

In [9]:
encoded_labels=le.fit_transform(data["LotShape"])
encoded_labels
data=data.drop(["LotShape"],axis=1)
data["LotShape"]=encoded_labels

,MSSubClass,MSZoning,LotFrontage,LotArea,LandContour,LotConfig,LandSlope,Condition1,Condition2,BldgType,...,3SsnPorch,ScreenPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Neighborhood,LotShape
0,60,RL,65.0,8450,Lvl,Inside,Gtl,Norm,Norm,1Fam,...,0,0,0,2,2008,WD,Normal,208500,5,3
1,20,RL,80.0,9600,Lvl,FR2,Gtl,Feedr,Norm,1Fam,...,0,0,0,5,2007,WD,Normal,181500,24,3
2,60,RL,68.0,11250,Lvl,Inside,Gtl,Norm,Norm,1Fam,...,0,0,0,9,2008,WD,Normal,223500,5,0
3,70,RL,60.0,9550,Lvl,Corner,Gtl,Norm,Norm,1Fam,...,0,0,0,2,2006,WD,Abnorml,140000,6,0
4,60,RL,84.0,14260,Lvl,FR2,Gtl,Norm,Norm,1Fam,...,0,0,0,12,2008,WD,Normal,250000,15,0

In [10]:
### Function to determine if an object within the data frame is an integer or not
def is_integer(n):
    try:
        float(n)
    except ValueError:
        return False
    else:
        return float(n).is_integer()

In [11]:
#print(is_integer(data["LotFrontage"][4]))
#print(is_integer(data["LotConfig"][2]))
is_integer(data["LotConfig"][4])

False

In [12]:
dataT=data.T
dataT.shape

(72, 1460)

In [13]:
data["LotArea"][3]

9550

In [14]:
data=data.interpolate(method='quadratic')
data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,LandContour,LotConfig,LandSlope,Condition1,Condition2,BldgType,...,3SsnPorch,ScreenPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Neighborhood,LotShape
0,60,RL,65.0,8450,Lvl,Inside,Gtl,Norm,Norm,1Fam,...,0,0,0,2,2008,WD,Normal,208500,5,3
1,20,RL,80.0,9600,Lvl,FR2,Gtl,Feedr,Norm,1Fam,...,0,0,0,5,2007,WD,Normal,181500,24,3
2,60,RL,68.0,11250,Lvl,Inside,Gtl,Norm,Norm,1Fam,...,0,0,0,9,2008,WD,Normal,223500,5,0
3,70,RL,60.0,9550,Lvl,Corner,Gtl,Norm,Norm,1Fam,...,0,0,0,2,2006,WD,Abnorml,140000,6,0
4,60,RL,84.0,14260,Lvl,FR2,Gtl,Norm,Norm,1Fam,...,0,0,0,12,2008,WD,Normal,250000,15,0

In [15]:
#List of items to be encoded (yes, it is unprofessional & rookie)
to_be_encoded=["MSZoning","LotShape","LandContour","LotConfig","LandSlope","Condition1",
                   "Condition2","BldgType","HouseStyle","RoofStyle","RoofMatl","Exterior1st","Exterior2nd","ExterQual",
                   "ExterCond","Foundation","BsmtQual","BsmtCond","BsmtExposure","BsmtFinType1","BsmtFinType2", 
                   "Heating","HeatingQC","CentralAir","Electrical","KitchenQual","Functional", "FireplaceQu","GarageType",
                    "GarageFinish", "GarageQual","GarageCond","PavedDrive","SaleType","SaleCondition"]
print(data[to_be_encoded[2]])            #It's legit
len(to_be_encoded)

0       Lvl
1       Lvl
2       Lvl
3       Lvl
4       Lvl
       ...
1455    Lvl
1456    Lvl
1457    Lvl
1458    Lvl
1459    Lvl
Name: LandContour, Length: 1460, dtype: object

35

In [16]:
for i in range(35):
    print(data[to_be_encoded[i]])
    data[to_be_encoded[i]] = pd.to_numeric(data[to_be_encoded[i]], errors='coerce')
    #encoded_labels=data[to_be_encoded[i]].apply(lambda col: le.fit_transform(col.astype(str)))
    encoded_labels=le.fit_transform(data[to_be_encoded[i]])
    encoded_labels
    data=data.drop([to_be_encoded[i]],axis=1)
    data[to_be_encoded[i]]=encoded_labels

0       RL
1       RL
2       RL
3       RL
4       RL
        ..
1455    RL
1456    RL
1457    RL
1458    RL
1459    RL
Name: MSZoning, Length: 1460, dtype: object
0       3
1       3
2       0
3       0
4       0
       ..
1455    3
1456    3
1457    3
1458    3
1459    3
Name: LotShape, Length: 1460, dtype: int32
0       Lvl
1       Lvl
2       Lvl
3       Lvl
4       Lvl
       ...
1455    Lvl
1456    Lvl
1457    Lvl
1458    Lvl
1459    Lvl
Name: LandContour, Length: 1460, dtype: object
0       Inside
1          FR2
2       Inside
3       Corner
4          FR2
         ...
1455    Inside
1456    Inside
1457    Inside
1458    Inside
1459    Inside
Name: LotConfig, Length: 1460, dtype: object
0       Gtl
1       Gtl
2       Gtl
3       Gtl
4       Gtl
       ...
1455    Gtl
1456    Gtl
1457    Gtl
1458    Gtl
1459    Gtl
Name: LandSlope, Length: 1460, dtype: object
0        Norm
1       Feedr
2        Norm
3        Norm
4        Norm
        ...
1455     Norm
1456     Norm
1457     Norm
1458     Norm
1459     Norm
Name: Condition1, Length: 1460, dtype: object
0       Norm
1       Norm
2       Norm
3       Norm
4       Norm
        ...
1455    Norm
1456    Norm
1457    Norm
1458    Norm
1459    Norm
Name: Condition2, Length: 1460, dtype: object
0       1Fam
1       1Fam
2       1Fam
3       1Fam
4       1Fam
        ...
1455    1Fam
1456    1Fam
1457    1Fam
1458    1Fam
1459    1Fam
Name: BldgType, Length: 1460, dtype: object
0       2Story
1       1Story
2       2Story
3       2Story
4       2Story
         ...
1455    2Story
1456    1Story
1457    2Story
1458    1Story
1459    1Story
Name: HouseStyle, Length: 1460, dtype: object
0       Gable
1       Gable
2       Gable
3       Gable
4       Gable
        ...
1455    Gable
1456    Gable
1457    Gable
1458      Hip
1459    Gable
Name: RoofStyle, Length: 1460, dtype: object
0       CompShg
1       CompShg
2       CompShg
3       CompShg
4       CompShg
         ...
1455    CompShg
1456    CompShg
1457    CompShg
1458    CompShg
1459    CompShg
Name: RoofMatl, Length: 1460, dtype: object
0       VinylSd
1       MetalSd
2       VinylSd
3       Wd Sdng
4       VinylSd
         ...
1455    VinylSd
1456    Plywood
1457    CemntBd
1458    MetalSd
1459    HdBoard
Name: Exterior1st, Length: 1460, dtype: object
0       VinylSd
1       MetalSd
2       VinylSd
3       Wd Shng
4       VinylSd
         ...
1455    VinylSd
1456    Plywood
1457    CmentBd
1458    MetalSd
1459    HdBoard
Name: Exterior2nd, Length: 1460, dtype: object
0       Gd
1       TA
2       Gd
3       TA
4       Gd
        ..
1455    TA
1456    TA
1457    Ex
1458    TA
1459    Gd
Name: ExterQual, Length: 1460, dtype: object
0       TA
1       TA
2       TA
3       TA
4       TA
        ..
1455    TA
1456    TA
1457    Gd
1458    TA
1459    TA
Name: ExterCond, Length: 1460, dtype: object
0        PConc
1       CBlock
2        PConc
3       BrkTil
4        PConc
         ...
1455     PConc
1456    CBlock
1457     Stone
1458    CBlock
1459    CBlock
Name: Foundation, Length: 1460, dtype: object
0       Gd
1       Gd
2       Gd
3       TA
4       Gd
        ..
1455    Gd
1456    Gd
1457    TA
1458    TA
1459    TA
Name: BsmtQual, Length: 1460, dtype: object
0       TA
1       TA
2       TA
3       Gd
4       TA
        ..
1455    TA
1456    TA
1457    Gd
1458    TA
1459    TA
Name: BsmtCond, Length: 1460, dtype: object
0       No
1       Gd
2       Mn
3       No
4       Av
        ..
1455    No
1456    No
1457    No
1458    Mn
1459    No
Name: BsmtExposure, Length: 1460, dtype: object
0       GLQ
1       ALQ
2       GLQ
3       ALQ
4       GLQ
       ...
1455    Unf
1456    ALQ
1457    GLQ
1458    GLQ
1459    BLQ
Name: BsmtFinType1, Length: 1460, dtype: object
0       Unf
1       Unf
2       Unf
3       Unf
4       Unf
       ...
1455    Unf
1456    Rec
1457    Unf
1458    Rec
1459    LwQ
Name: BsmtFinType2, Length: 1460, dtype: object
0       GasA
1       GasA
2       GasA
3       GasA
4       GasA
        ...
1455    GasA
1456    GasA
1457    GasA
1458    GasA
1459    GasA
Name: Heating, Length: 1460, dtype: object
0       Ex
1       Ex
2       Ex
3       Gd
4       Ex
        ..
1455    Ex
1456    TA
1457    Ex
1458    Gd
1459    Gd
Name: HeatingQC, Length: 1460, dtype: object
0       Y
1       Y
2       Y
3       Y
4       Y
       ..
1455    Y
1456    Y
1457    Y
1458    Y
1459    Y
Name: CentralAir, Length: 1460, dtype: object
0       SBrkr
1       SBrkr
2       SBrkr
3       SBrkr
4       SBrkr
        ...
1455    SBrkr
1456    SBrkr
1457    SBrkr
1458    FuseA
1459    SBrkr
Name: Electrical, Length: 1460, dtype: object
0       Gd
1       TA
2       Gd
3       Gd
4       Gd
        ..
1455    TA
1456    TA
1457    Gd
1458    Gd
1459    TA
Name: KitchenQual, Length: 1460, dtype: object
0        Typ
1        Typ
2        Typ
3        Typ
4        Typ
        ...
1455     Typ
1456    Min1
1457     Typ
1458     Typ
1459     Typ
Name: Functional, Length: 1460, dtype: object
0       NaN
1        TA
2        TA
3        Gd
4        TA
       ...
1455     TA
1456     TA
1457     Gd
1458    NaN
1459    NaN
Name: FireplaceQu, Length: 1460, dtype: object
0       Attchd
1       Attchd
2       Attchd
3       Detchd
4       Attchd
         ...
1455    Attchd
1456    Attchd
1457    Attchd
1458    Attchd
1459    Attchd
Name: GarageType, Length: 1460, dtype: object
0       RFn
1       RFn
2       RFn
3       Unf
4       RFn
       ...
1455    RFn
1456    Unf
1457    RFn
1458    Unf
1459    Fin
Name: GarageFinish, Length: 1460, dtype: object
0       TA
1       TA
2       TA
3       TA
4       TA
        ..
1455    TA
1456    TA
1457    TA
1458    TA
1459    TA
Name: GarageQual, Length: 1460, dtype: object
0       TA
1       TA
2       TA
3       TA
4       TA
        ..
1455    TA
1456    TA
1457    TA
1458    TA
1459    TA
Name: GarageCond, Length: 1460, dtype: object
0       Y
1       Y
2       Y
3       Y
4       Y
       ..
1455    Y
1456    Y
1457    Y
1458    Y
1459    Y
Name: PavedDrive, Length: 1460, dtype: object
0       WD
1       WD
2       WD
3       WD
4       WD
        ..
1455    WD
1456    WD
1457    WD
1458    WD
1459    WD
Name: SaleType, Length: 1460, dtype: object
0        Normal
1        Normal
2        Normal
3       Abnorml
4        Normal
         ...
1455     Normal
1456     Normal
1457     Normal
1458     Normal
1459     Normal
Name: SaleCondition, Length: 1460, dtype: object

In [17]:
""" 
#data_encoded = data.apply(LabelEncoder.fit_transform)
#data_encoded[:,0]=le.fit_transform(data[:,0])
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder()

data_encoded=oh.fit_transform(data).toarray()
print(data_encoded) """

' \n#data_encoded = data.apply(LabelEncoder.fit_transform)\n#data_encoded[:,0]=le.fit_transform(data[:,0])\nfrom sklearn.preprocessing import OneHotEncoder\noh=OneHotEncoder()\n\ndata_encoded=oh.fit_transform(data).toarray()\nprint(data_encoded) '

In [18]:
data.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,0,0,0,0,0,0,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,976,976,976,976,976,976,976,976,976,976
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,975,975,975,975,975,975,975,975,975,975
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,974,974,974,974,974,974,974,974,974,974
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,973,973,973,973,973,973,973,973,973,973

In [29]:
X=data.drop(["SalePrice"],axis=1)

print(X.shape)

(1460, 71)